name: ini cd golang
on:
  push:
    branches:
      - "master"
jobs:
  testing:
    runs-on: ubuntu-latest
    name: "ini unitest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run unit test
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    name: "ini deploy"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # Setup Heroku
      - name: Setup Heroku CLI
        run: sudo curl https://cli-assets.heroku.com/install.sh | sh

      # - name: Login Heroku
      #   run: |
      #     heroku login -i
      #     echo andinugraha1399@gmail.com
      #     echo ${{ secrets.HEROKU_PASSWORD }}
      #     heroku access
          
          

      # Setup Heroku Git
      - name: Setup Heroku GIT
        run: |
          rm -rf .git
          git init
          git config --global user.name "AndiAnugrahAqsa"
          git config --global user.email andianugrahaqsa@gmail.com
          git add .
          git commit -m "ROCK YOU"
          git remote add heroku https://heroku:6fd5dd3f-14a1-438b-9e3b-82805046df79@git.heroku.com/test-deployy111.git
          git remote -v
      
       # Push New Changes
      - name: Push new changes to heroku
        run: |
          git push -f heroku master