name: ini cd golang
on:
  push:
    branches:
      - "master"
jobs:
  testing:
    runs-on: ubuntu-latest
    name: "ini unitest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run unit test
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    name: "ini deploy"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # Setup Heroku
      - name: Setup Heroku CLI
        run: sudo curl https://cli-assets.heroku.com/install.sh | sh         
          

      # Setup Heroku Git
      - name: Setup Heroku GIT
        env:
          TOKEN: ${{ secrets.HEROKU_TOKEN }}
          APP: ${{ secrets.HEROKU_APP }}
        run: |
          rm -rf .git
          git init
          git config --global user.name "AndiAnugrahAqsa"
          git config --global user.email andianugrahaqsa@gmail.com
          git add .
          git commit -m "ROCK YOU"
          git remote add heroku https://heroku:$TOKEN@git.heroku.com/$APP.git
          git remote -v
      
       # Push New Changes
      - name: Push new changes to heroku
        run: |
          git push -f heroku master